name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '14'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate target platform
        run: mvn clean verify -f releng/nl.tno.capella.workflow.dse.target/pom.xml
      - name: Build
        run: mvn clean verify
      - uses: actions/upload-artifact@v3
        with:
          path: releng/nl.tno.capella.workflow.dse.product/dist/*
